### ISSUE TITLE
Failed to set installation files to private

### ISSUE THREAD

**Issue by hagrace4** [trafficpest/strikeout#2]
I am running the webapp in a local docker container.
Here is my Dockerfile:
```
# Use an official PHP runtime as a parent image with Apache
FROM php:7.4-apache

# Set working directory in the container
WORKDIR /var/www/html

# Copy local content into the container
COPY . .

# Install unzip
RUN apt-get update && \
    apt-get install -y unzip

# Unzip strikeout file and move it to the desired location
RUN unzip strikeout-1.0.0-rc.4.zip && \
    rm strikeout-1.0.0-rc.4.zip && \
    mv strikeout-1.0.0-rc.4 strikeout

# Change ownership of the 'strikeout' directory
RUN chown -R www-data:www-data strikeout

# Make port 80 available to the world outside this container
EXPOSE 80
``` 

Upon Configuration within the webapp I am prompted with the follow warning.
```
Warning: fileperms(): stat failed for ../logs in /var/www/html/strikeout/inc/configure.php on line 66
```
![image](https://github.com/trafficpest/strikeout/assets/36256262/5ed1a7c1-ecb5-41e5-88bf-3064f76a0f80)

When pressing "Set" I am then given another Warning:
```
Warning: chmod(): No such file or directory in /var/www/html/strikeout/inc/configure.php on line 59
```

**Comment by trafficpest** [comment]
Looks like file permissions problems does php have permission to alter the folder? it could also be a path to root problem. what page did you get this error.

There is a docker setup for strikeout here https://github.com/trafficpest/strikeout-docker

it uses debian slim to be compatable with umbrel it has php sql and nginx.

I havent tested it much but it was working recently
